### ISSUE TITLE
Support for other video provider

### ISSUE THREAD

**Issue by MazzMazz** [codeclown/FloatPlayer#3]
We could extend this application with youtube-dl https://github.com/rg3/youtube-dl/blob/master/README.md#readme

**Comment by codeclown** [comment]
youtube-dl is meant for download raw video files from video services. This app doesn't do that.

FloatPlayer embeds a YouTube iframe player in a WKWebView. To implement other video services their corresponding embed APIs should be used. I'm open to PRs in this fashion.
